# Generated by Django 5.0 on 2024-11-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.users')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('users.users',),
        ),
        migrations.AddField(
            model_name='guide',
            name='expertise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='permission',
            field=models.CharField(choices=[('GUIDE', 'Guide'), ('TRAINEE_GUIDE', 'Trainee Guide')], default='TRAINEE_GUIDE', max_length=20),
        ),
    ]
