# Generated by Django 5.0 on 2024-11-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.users')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            bases=('users.users',),
        ),
    ]
