# Generated by Django 5.0 on 2024-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='applicantName',
            new_name='counselarName',
        ),
        migrations.AddField(
            model_name='tour',
            name='counselarPhoneNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='schoolName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
