# Generated by Django 5.0 on 2024-11-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_applicantname_tour_counselarname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='id',
        ),
        migrations.AddField(
            model_name='tour',
            name='counselarEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='counselarPosition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='schoolCity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tourId',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.CharField(choices=[('1', '09.00'), ('2', '11.00'), ('3', '13.00'), ('4', '15.00')], max_length=1, null=True),
        ),
    ]
